# Generated by Django 5.0.6 on 2024-07-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_time', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=300)),
                ('job_location', models.CharField(max_length=200)),
                ('job_price', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
