# Generated by Django 5.0.6 on 2024-07-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h4',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h5',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h6',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_img',
            field=models.ImageField(default='static/img/career/gr1.png', upload_to='img/career/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_info_p',
            field=models.TextField(default="Rétrouvez ci-dessous les informations nécessaires pour pouvoir postuler à cette offre d'emploi."),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_info_title',
            field=models.CharField(default="Information sur l'offre d'emploi", max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li1',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li2',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li3',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li4',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li5',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li6',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_p',
            field=models.TextField(default='#'),
        ),
    ]
