# Generated by Django 5.0.6 on 2024-07-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_jobs_job_date_jobs_job_h4_jobs_job_h5_jobs_job_h6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_li7',
            field=models.TextField(default='#', max_length=300),
        ),
    ]
