# Generated by Django 5.0.6 on 2024-07-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_jobs_job_li7'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_h51',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h61',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h62',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h63',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h64',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_h65',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_img1',
            field=models.ImageField(default='static/img/career/gr1.png', upload_to='img/career/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_img2',
            field=models.ImageField(default='static/img/career/gr1.png', upload_to='img/career/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_img3',
            field=models.ImageField(default='static/img/career/gr1.png', upload_to='img/career/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_img4',
            field=models.ImageField(default='static/img/career/gr1.png', upload_to='img/career/'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li10',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li11',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li12',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li13',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li14',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li15',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li8',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_li9',
            field=models.TextField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_p1',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_p2',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_p3',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_p4',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_p5',
            field=models.TextField(default='#'),
        ),
    ]
