# Generated by Django 5.0.6 on 2024-07-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_jobs_job_h51_jobs_job_h61_jobs_job_h62_jobs_job_h63_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_h65',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job_p5',
        ),
    ]
