# Generated by Django 5.0.6 on 2024-07-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=200)),
                ('categorie_section', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_img', models.ImageField(default='static/img/portfolio/1.jpg', upload_to='img/portfolio/')),
                ('portfolio_date', models.DateField(auto_now=True)),
                ('portfolio_title', models.CharField(default='#', max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='Projects.categories_portfolio')),
            ],
        ),
    ]
