# Generated by Django 5.0.6 on 2024-07-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_demande',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_demande1',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_detail',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='equipe_job',
            field=models.CharField(default='#', max_length=600),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='equipe_job1',
            field=models.CharField(default='#', max_length=600),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='equipe_name',
            field=models.CharField(default='#', max_length=600),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='equipe_name1',
            field=models.CharField(default='#', max_length=600),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_h5',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_projects',
            field=models.ImageField(blank=True, upload_to='img/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_projects1',
            field=models.ImageField(blank=True, upload_to='img/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_projects2',
            field=models.ImageField(blank=True, upload_to='img/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_projects3',
            field=models.ImageField(blank=True, upload_to='img/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_projects4',
            field=models.ImageField(blank=True, upload_to='img/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_projects5',
            field=models.ImageField(blank=True, upload_to='img/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_p',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_p1',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_p2',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_p3',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_p4',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_video_img',
            field=models.ImageField(default='static/img/portfolio/video-img.jpg', upload_to='img/portfolio/'),
        ),
    ]
