# Generated by Django 5.0.6 on 2024-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_portfolio_client_portfolio_client_demande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_p4',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_title',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_title1',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_title2',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_title3',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_title4',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img_title5',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_h5',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
