# Generated by Django 5.0.6 on 2024-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, default='img/banner/banner_1.jpg', upload_to='static/img/banner/')),
                ('banner_span', models.CharField(max_length=200)),
                ('banner_titre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='home_datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_img', models.ImageField(blank=True, default='img/feature/icon1.png', upload_to='static/img/feature/')),
                ('features_titre', models.CharField(max_length=200)),
                ('features_span', models.CharField(default='#', max_length=200)),
                ('about_h_ceo_img', models.ImageField(blank=True, default='img/about/ceo.jpg', upload_to='static/img/about/')),
                ('about_h_video_link', models.CharField(default='#', max_length=1000)),
                ('about_h_span', models.CharField(default='#', max_length=200)),
                ('about_h_titre', models.CharField(default='#', max_length=200)),
                ('about_h_p1', models.TextField(default='#')),
                ('about_h_p2', models.TextField(default='#')),
            ],
        ),
    ]
