# Generated by Django 5.0.6 on 2024-07-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_datas', '0005_alter_testimonials_h_review_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_datas',
            name='about_ceo_fonction',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='home_datas',
            name='about_ceo_name',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='home_datas',
            name='about_img',
            field=models.ImageField(blank=True, upload_to='img/about/'),
        ),
    ]
