# Generated by Django 5.0.6 on 2024-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_datas', '0006_home_datas_about_ceo_fonction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='home_datas',
            name='h_feature_img',
            field=models.ImageField(blank=True, default='img/about/signature.png', upload_to='img/feature/'),
        ),
    ]
