# Generated by Django 5.0.6 on 2024-07-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_datas', '0007_contactindex_alter_home_datas_h_feature_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(blank=True, upload_to='img/team/')),
                ('about_link', models.CharField(max_length=500)),
                ('about_titre', models.CharField(default='#', max_length=200)),
                ('about_p1', models.TextField(default='#')),
                ('about_p2', models.TextField(default='#')),
                ('about_img1', models.ImageField(blank=True, upload_to='img/about/')),
                ('about_ceo_name', models.CharField(default='#', max_length=200)),
                ('about_ceo_fonction', models.CharField(default='#', max_length=200)),
                ('about_h2', models.CharField(default='#', max_length=255)),
                ('about_p3', models.TextField(default='#')),
                ('about_p4', models.TextField(default='#')),
                ('about_h2_1', models.CharField(default='#', max_length=255)),
                ('about_p5', models.TextField(default='#')),
                ('about_li', models.TextField(default='#')),
                ('about_li1', models.TextField(default='#')),
                ('about_li2', models.TextField(default='#')),
                ('about_li3', models.TextField(default='#')),
                ('about_li4', models.TextField(default='#')),
            ],
        ),
    ]
