# Generated by Django 5.0.6 on 2024-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_datas', '0008_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='about_img',
            field=models.ImageField(blank=True, upload_to='img/about/'),
        ),
    ]
