# Generated by Django 5.0.6 on 2024-08-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_datas', '0009_alter_about_us_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
