# Generated by Django 5.0.6 on 2024-07-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_span', models.CharField(max_length=100)),
                ('clients_title', models.CharField(max_length=255)),
                ('clients_img', models.ImageField(blank=True, upload_to='img/clients/')),
                ('clients_alt', models.CharField(max_length=300)),
                ('clients_name', models.CharField(max_length=255)),
            ],
        ),
    ]
