# Generated by Django 5.0.6 on 2024-07-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_alter_clients_clients_span_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_mono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_titre', models.CharField(max_length=255)),
                ('terms_p1', models.TextField(default='#')),
                ('terms_p2', models.TextField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='Terms_multi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_titre2', models.CharField(max_length=255)),
                ('terms_p', models.TextField(default='#')),
                ('terms_li', models.TextField(default='#')),
                ('terms_li1', models.TextField(default='#')),
                ('terms_li2', models.TextField(default='#')),
                ('terms_li3', models.TextField(default='#')),
                ('terms_li4', models.TextField(default='#')),
                ('terms_li5', models.TextField(default='#')),
                ('terms_li6', models.TextField(default='#')),
                ('terms_li7', models.TextField(default='#')),
            ],
        ),
    ]
