# Generated by Django 5.0.6 on 2024-07-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='id_unique',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
