# Generated by Django 5.0.6 on 2024-08-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_siteconfiguration_delete_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(blank=True, max_length=500)),
                ('faq_h5', models.CharField(blank=True, max_length=300)),
                ('faq_body', models.TextField(blank=True)),
                ('faq_h5_1', models.CharField(blank=True, max_length=300)),
                ('faq_body1', models.TextField(blank=True)),
                ('faq_h5_2', models.CharField(blank=True, max_length=300)),
                ('faq_body2', models.TextField(blank=True)),
                ('faq_h5_3', models.CharField(blank=True, max_length=300)),
                ('faq_body3', models.TextField(blank=True)),
            ],
        ),
    ]
