# Generated by Django 5.0.6 on 2024-08-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
