# Generated by Django 5.0.6 on 2024-08-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('name_compagny', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('services', models.CharField(blank=True, max_length=800)),
                ('projects_details', models.TextField(blank=True)),
                ('budget', models.CharField(blank=True, max_length=800)),
                ('date_start', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('call_date', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=300)),
                ('feedbak', models.TextField(blank=True)),
            ],
        ),
    ]
