# Generated by Django 5.0.6 on 2024-08-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0011_devisform_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devisform',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
