# Generated by Django 5.0.6 on 2024-08-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_remove_devisform_fullname_devisform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisform',
            name='identifiant',
            field=models.CharField(default='identifiant-1', max_length=1000),
        ),
    ]
