# Generated by Django 5.0.6 on 2024-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_h1', models.CharField(max_length=300)),
                ('services_span', models.CharField(max_length=200)),
                ('services_icon', models.ImageField(blank=True, upload_to='static/img/service/')),
                ('services_title', models.CharField(max_length=300)),
                ('services_brief', models.CharField(max_length=200)),
                ('services_link', models.CharField(max_length=500)),
                ('services_p1', models.TextField()),
                ('services_p2', models.TextField()),
                ('services_p3', models.TextField()),
                ('services_p4', models.TextField()),
                ('services_sous_titre', models.CharField(max_length=300)),
                ('services_liste1', models.TextField()),
                ('services_liste2', models.TextField()),
                ('services_liste3', models.TextField()),
                ('services_liste4', models.TextField()),
                ('services_liste5', models.TextField()),
                ('services_liste6', models.TextField()),
                ('services_faq_title1', models.CharField(max_length=300)),
                ('services_faq_content1', models.TextField()),
                ('services_faq_title2', models.CharField(max_length=300)),
                ('services_faq_content2', models.TextField()),
                ('services_faq_title3', models.CharField(max_length=300)),
                ('services_faq_content3', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
