# Generated by Django 5.0.6 on 2024-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='services_h1',
            field=models.CharField(default='Nos services', max_length=300),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_span',
            field=models.CharField(default='Découvrez Nos Services', max_length=200),
        ),
    ]
