# Generated by Django 5.0.6 on 2024-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_services_services_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='services_icon',
            field=models.ImageField(blank=True, upload_to='img/service/'),
        ),
    ]
