# Generated by Django 5.0.6 on 2024-07-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_services_services_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='services_link',
        ),
    ]
