# Generated by Django 5.0.6 on 2024-07-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_posts_post_img_alter_posts_post_img_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_section', models.CharField(max_length=200)),
                ('cat_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='Blog.categories'),
        ),
    ]
