# Generated by Django 5.0.6 on 2024-07-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_categories_posts_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['post_day']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
