# Generated by Django 5.0.6 on 2024-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_posts_options_alter_posts_post_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_day',
            field=models.DateField(),
        ),
    ]
