# Generated by Django 5.0.6 on 2024-07-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_posts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_author_desc',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_author_principal',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
